# Generated by Django 2.0.3 on 2018-05-03 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trash_type', models.CharField(blank=True, choices=[('R', 'Recycle'), ('C', 'Compost')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 5, 3, 10, 35, 52, 772398))),
                ('image_file', models.CharField(default='<django.db.models.fields.DateTimeField>', max_length=500)),
            ],
        ),
    ]
