# Generated by Django 2.0.3 on 2018-05-03 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 11, 43, 54, 328348)),
        ),
    ]
