# Generated by Django 2.0.3 on 2018-05-03 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0003_auto_20180503_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 16, 10, 31, 638746)),
        ),
    ]
